services:

  # PHP-FPM (Laravel App)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pga_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - storage_data:/var/www/storage
    networks:
      - pga_network
    depends_on:
      - mysql

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: pga_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pga_network
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: pga_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - pga_mysql_data:/var/lib/mysql
    networks:
      - pga_network

networks:
  pga_network:
    driver: bridge

volumes:
  pga_mysql_data:
    driver: local
  storage_data: